# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.1

pipelines:
  branches:
    master:
     - step:
        name: Build
        script:
          - yarn install
          - yarn run build
     - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-west-2"
              S3_BUCKET: "coin-keeper-parser"
              LOCAL_PATH: "build"
              ACL: "public-read"
              CACHE_CONTROL: "max-age=3600"
              EXPIRES: "2018-10-01T00:00:00+00:00"
              DELETE_FLAG: "true"
              EXTRA_ARGS: "--follow-symlinks"